version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # group updates in a single PR
    groups:
      actions:
        patterns:
          - "*"
